[target.aarch64-linux-android]
linker = "/home/pankaj/android-build-tools/android-sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android34-clang"
rustflags = ["-C", "link-arg=-L/home/pankaj/android-build-tools/android-sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/34", "-l", "log"]
